name: 'is-tag-reachable-from-default-branch'

description: 'Determines whether a tag is reachable from the default branch'

inputs:
  tag:
    description: 'The tag to be checked'
    required: true
  default-branch:
    description: 'The default branch for the repository.  Defaults to main.'
    required: true
    default: 'main'
  ref:
    description: 'The default branch for the repository.  Defaults to main.'
    required: false
  error-if-not-reachable:
    description: 'Throw an error if the tag is not reachable from the default branch'
    required: true
    default: 'true'

outputs:
  reachable:
    description: 'Whether the tag is reachable from the default branch.'
    value: '${{ steps.check-tag.outputs.reachable }}'

runs:
  using: 'composite'
  steps:
  
    # ${REF##*/} removes any prefixes
    - name: Check if tag is reachable from the default branch
      id: check-tag
      shell: bash
      env:
        GITHUB_TAG: ${{ steps.remove-prefix.outputs.result }}
        GITHUB_DEFAULT_BRANCH: ${{ inputs.default-branch }}
        GITHUB_REF: ${{ inputs.ref }}
      run: |
        errorIfNotReachable=${{ inputs.error-if-not-reachable }}
        tag=${GITHUB_TAG##*/}
        defaultBranch=${GITHUB_DEFAULT_BRANCH##*/}
        ref=${GITHUB_REF##*/}

        echo "Checking tag: $tag"
        echo "ErrorIfNotReachable: $errorIfNotReachable"

        if [ $(echo ${#ref}) -gt 0 ]; then
          echo "::group::Switching to the default branch"
          git checkout $defaultBranch -f
          echo "::endgroup::"
        fi

        mergedTags=$(git tag --merged)

        echo "Checking tag: $tag"
        echo "::group::The repository contains the following tags which are reachable from $defaultBranch"
        printf '%s\n' "${mergedTags[@]}"
        echo "::endgroup::"

        if [ $(echo ${#ref}) -gt 0 ]; then
          echo "::group::Switching back to $ref"
          git checkout $ref -f
          echo "::endgroup::"
        fi       

        if printf '%s\n' "${mergedTags[@]}" | grep -q -w $tag ; 
        then
          echo "The tag appears in the list of reachable tags"
          echo "::set-output name=reachable::true"
        else
          echo "::error::The tag does not appear to be reachable by from $defaultBranch."
          echo "::set-output name=reachable::false"
          if [ "$errorIfNotReachable" == "true" ]; then
            exit 1
          fi
        fi
